Repository SWM-KAWAI-MANS/party-run-authentication-service, pull requests merged in 2023-06, with the labels that each got.

#2 통합시 google format에 맞추어 수정된 후 통합되도록 설정
  .github/workflows/reformat-java.yml
Labels: 🏭인프라

#1 AuthController 관련 테스트 작성
  build.gradle
  src/docs/auth.adoc
  src/docs/index.adoc
  src/main/generated/online/partyrun/partyrunauthenticationservice/domain/member/dto/MemberMapperImpl.java
  src/main/java/online/partyrun/partyrunauthenticationservice/domain/auth/service/FirebaseAuthService.java
  src/main/java/online/partyrun/partyrunauthenticationservice/domain/member/dto/MemberResponse.java
  src/main/java/online/partyrun/partyrunauthenticationservice/global/controller/HttpControllerAdvice.java
  src/main/resources/application.yml
  src/test/java/online/partyrun/partyrunauthenticationservice/config/docs/ApiDocumentUtils.java
  src/test/java/online/partyrun/partyrunauthenticationservice/config/docs/RestDocsConfiguration.java
  src/test/java/online/partyrun/partyrunauthenticationservice/config/docs/RestDocumentTest.java
  src/test/java/online/partyrun/partyrunauthenticationservice/domain/auth/controller/AuthControllerTest.java
Labels: ✨ 기능

#3 단위 테스트, 통합 테스트 추가
  .gitignore
  build.gradle
  src/main/generated/online/partyrun/partyrunauthenticationservice/domain/member/dto/MemberMapperImpl.java
  src/main/java/online/partyrun/partyrunauthenticationservice/domain/auth/service/firebase/FirebaseAuthService.java
  src/main/java/online/partyrun/partyrunauthenticationservice/domain/auth/service/firebase/FirebaseHandler.java
  src/main/java/online/partyrun/partyrunauthenticationservice/domain/auth/service/firebase/TokenResponse.java
  src/main/java/online/partyrun/partyrunauthenticationservice/domain/member/dto/MemberResponse.java
  src/main/java/online/partyrun/partyrunauthenticationservice/domain/token/entity/RefreshToken.java
  src/main/java/online/partyrun/partyrunauthenticationservice/domain/token/exception/EmptyStringException.java
  src/main/java/online/partyrun/partyrunauthenticationservice/global/config/FirebaseConfig.java
  src/main/java/online/partyrun/partyrunauthenticationservice/global/config/RedisConfig.java
  src/main/resources/application.yml
  src/test/java/online/partyrun/partyrunauthenticationservice/config/RedisTestConfig.java
  src/test/java/online/partyrun/partyrunauthenticationservice/domain/auth/service/FirebaseAuthServiceTest.java
  src/test/java/online/partyrun/partyrunauthenticationservice/domain/member/service/MemberServiceTest.java
  src/test/java/online/partyrun/partyrunauthenticationservice/domain/token/entity/RefreshTokenTest.java
Labels: ♻️ 리팩토링

#4 파이어베이스 인증을 진행한다.
  .gitignore
  build.gradle
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
  gradlew
  gradlew.bat
  settings.gradle
  src/docs/auth.adoc
  src/docs/index.adoc
  src/main/java/online/partyrun/partyrunauthenticationservice/PartyRunAuthenticationServiceApplication.java
  src/main/java/online/partyrun/partyrunauthenticationservice/domain/auth/controller/AuthController.java
  src/main/java/online/partyrun/partyrunauthenticationservice/domain/auth/dto/AccessTokenResponse.java
  src/main/java/online/partyrun/partyrunauthenticationservice/domain/auth/dto/IdTokenRequest.java
  src/main/java/online/partyrun/partyrunauthenticationservice/domain/auth/exception/IllegalIdTokenException.java
  src/main/java/online/partyrun/partyrunauthenticationservice/domain/auth/exception/NoSuchRefreshTokenException.java
  src/main/java/online/partyrun/partyrunauthenticationservice/domain/auth/service/AuthService.java
  src/main/java/online/partyrun/partyrunauthenticationservice/domain/auth/service/firebase/FirebaseAuthService.java
  src/main/java/online/partyrun/partyrunauthenticationservice/domain/auth/service/firebase/FirebaseHandler.java
  src/main/java/online/partyrun/partyrunauthenticationservice/domain/auth/service/firebase/TokenResponse.java
  src/main/java/online/partyrun/partyrunauthenticationservice/domain/member/dto/MemberMapper.java
  src/main/java/online/partyrun/partyrunauthenticationservice/domain/member/dto/MemberRequest.java
  src/main/java/online/partyrun/partyrunauthenticationservice/domain/member/dto/MemberResponse.java
  src/main/java/online/partyrun/partyrunauthenticationservice/domain/member/entity/Member.java
  src/main/java/online/partyrun/partyrunauthenticationservice/domain/member/repository/MemberRepository.java
  src/main/java/online/partyrun/partyrunauthenticationservice/domain/member/service/MemberService.java
  src/main/java/online/partyrun/partyrunauthenticationservice/domain/token/entity/RefreshToken.java
  src/main/java/online/partyrun/partyrunauthenticationservice/domain/token/exception/EmptyStringException.java
  src/main/java/online/partyrun/partyrunauthenticationservice/domain/token/repository/RefreshTokenRepository.java
  src/main/java/online/partyrun/partyrunauthenticationservice/global/config/FirebaseConfig.java
  src/main/java/online/partyrun/partyrunauthenticationservice/global/config/RedisConfig.java
  src/main/java/online/partyrun/partyrunauthenticationservice/global/controller/ExceptionResponse.java
  src/main/java/online/partyrun/partyrunauthenticationservice/global/controller/HttpControllerAdvice.java
  src/main/java/online/partyrun/partyrunauthenticationservice/global/exception/BadRequestException.java
  src/main/java/online/partyrun/partyrunauthenticationservice/global/exception/InternalServerErrorException.java
  src/main/java/online/partyrun/partyrunauthenticationservice/global/exception/UnAuthorizedException.java
  src/main/resources/application.yml
  src/test/java/online/partyrun/partyrunauthenticationservice/PartyRunAuthenticationServiceApplicationTests.java
  src/test/java/online/partyrun/partyrunauthenticationservice/config/RedisTestConfig.java
  src/test/java/online/partyrun/partyrunauthenticationservice/config/docs/ApiDocumentUtils.java
  src/test/java/online/partyrun/partyrunauthenticationservice/config/docs/RestDocsConfiguration.java
  src/test/java/online/partyrun/partyrunauthenticationservice/config/docs/RestDocumentTest.java
  src/test/java/online/partyrun/partyrunauthenticationservice/domain/auth/controller/AuthControllerTest.java
  src/test/java/online/partyrun/partyrunauthenticationservice/domain/auth/service/FirebaseAuthServiceTest.java
  src/test/java/online/partyrun/partyrunauthenticationservice/domain/member/repository/MemberRepositoryTest.java
  src/test/java/online/partyrun/partyrunauthenticationservice/domain/member/service/MemberServiceTest.java
  src/test/java/online/partyrun/partyrunauthenticationservice/domain/token/entity/RefreshTokenTest.java
Labels: ✨ 기능

#5 테스트 코드 리팩토링 및 rest docs 설정 변경
  build.gradle
  src/docs/asciidoc/auth.adoc
  src/docs/asciidoc/index.adoc
  src/main/java/online/partyrun/partyrunauthenticationservice/global/config/RedisConfig.java
  src/main/resources/application.yml
  src/test/java/online/partyrun/partyrunauthenticationservice/config/RedisTestConfig.java
  src/test/java/online/partyrun/partyrunauthenticationservice/config/docs/RestDocsConfiguration.java
  src/test/java/online/partyrun/partyrunauthenticationservice/config/docs/RestDocumentTest.java
  src/test/java/online/partyrun/partyrunauthenticationservice/domain/auth/controller/AuthControllerTest.java
Labels: ♻️ 리팩토링, ✨ 기능

#7 github action을 설정한다.
  .github/workflows/build.yml
  .github/workflows/reformat-java.yml
  src/main/java/online/partyrun/partyrunauthenticationservice/domain/auth/controller/AuthController.java
  src/main/java/online/partyrun/partyrunauthenticationservice/domain/auth/dto/AccessTokenResponse.java
  src/main/java/online/partyrun/partyrunauthenticationservice/domain/auth/dto/IdTokenRequest.java
  src/main/java/online/partyrun/partyrunauthenticationservice/domain/auth/service/AuthService.java
  src/main/java/online/partyrun/partyrunauthenticationservice/domain/auth/service/firebase/FirebaseAuthService.java
  src/main/java/online/partyrun/partyrunauthenticationservice/domain/auth/service/firebase/FirebaseHandler.java
  src/main/java/online/partyrun/partyrunauthenticationservice/domain/auth/service/firebase/TokenResponse.java
  src/main/java/online/partyrun/partyrunauthenticationservice/domain/member/dto/MemberMapper.java
  src/main/java/online/partyrun/partyrunauthenticationservice/domain/member/dto/MemberRequest.java
  src/main/java/online/partyrun/partyrunauthenticationservice/domain/member/dto/MemberResponse.java
  src/main/java/online/partyrun/partyrunauthenticationservice/domain/member/entity/Member.java
  src/main/java/online/partyrun/partyrunauthenticationservice/domain/member/repository/MemberRepository.java
  src/main/java/online/partyrun/partyrunauthenticationservice/domain/member/service/MemberService.java
  src/main/java/online/partyrun/partyrunauthenticationservice/domain/token/entity/RefreshToken.java
  src/main/java/online/partyrun/partyrunauthenticationservice/domain/token/repository/RefreshTokenRepository.java
  src/main/java/online/partyrun/partyrunauthenticationservice/global/config/FirebaseConfig.java
  src/main/java/online/partyrun/partyrunauthenticationservice/global/controller/ExceptionResponse.java
  src/main/java/online/partyrun/partyrunauthenticationservice/global/controller/HttpControllerAdvice.java
  src/main/resources/application.yml
  src/test/java/online/partyrun/partyrunauthenticationservice/PartyRunAuthenticationServiceApplicationTests.java
  src/test/java/online/partyrun/partyrunauthenticationservice/config/RedisTestConfig.java
  src/test/java/online/partyrun/partyrunauthenticationservice/config/docs/ApiDocumentUtils.java
  src/test/java/online/partyrun/partyrunauthenticationservice/config/docs/RestDocumentTest.java
  src/test/java/online/partyrun/partyrunauthenticationservice/domain/auth/controller/AuthControllerTest.java
  src/test/java/online/partyrun/partyrunauthenticationservice/domain/auth/service/FirebaseAuthServiceTest.java
  src/test/java/online/partyrun/partyrunauthenticationservice/domain/member/repository/MemberRepositoryTest.java
  src/test/java/online/partyrun/partyrunauthenticationservice/domain/member/service/MemberServiceTest.java
  src/test/java/online/partyrun/partyrunauthenticationservice/domain/token/entity/RefreshTokenTest.java
Labels: ✨ 기능, 🐛 버그

#9 CD 작업을 구성한다.
  .github/workflows/cd-dev.yml
  appspec.yml
  build.gradle
  deploy.sh
  src/main/resources/application.yml
Labels: 🏭인프라

#10 test-manager, authorization-manager 적용 및 Jwt token refresh시에 refresh token 도 갱신해서 반영하도록 변경 #PAR-49
  build.gradle
  src/main/java/online/partyrun/partyrunauthenticationservice/domain/auth/controller/AuthController.java
  src/main/java/online/partyrun/partyrunauthenticationservice/domain/auth/dto/AccessTokenResponse.java
  src/main/java/online/partyrun/partyrunauthenticationservice/domain/auth/service/AuthService.java
  src/main/java/online/partyrun/partyrunauthenticationservice/domain/auth/service/firebase/FirebaseAuthService.java
  src/main/java/online/partyrun/partyrunauthenticationservice/domain/member/dto/MemberResponse.java
  src/main/java/online/partyrun/partyrunauthenticationservice/domain/member/entity/Member.java
  src/main/java/online/partyrun/partyrunauthenticationservice/domain/member/entity/Role.java
  src/main/java/online/partyrun/partyrunauthenticationservice/global/controller/HttpControllerAdvice.java
  src/main/resources/application.yml
  src/test/java/online/partyrun/partyrunauthenticationservice/config/RedisTestConfig.java
  src/test/java/online/partyrun/partyrunauthenticationservice/config/docs/ApiDocumentUtils.java
  src/test/java/online/partyrun/partyrunauthenticationservice/config/docs/RestDocumentTest.java
  src/test/java/online/partyrun/partyrunauthenticationservice/domain/auth/controller/AuthControllerTest.java
  src/test/java/online/partyrun/partyrunauthenticationservice/domain/auth/service/FirebaseAuthServiceTest.java
  src/test/java/online/partyrun/partyrunauthenticationservice/domain/member/service/MemberServiceTest.java
Labels: ✨ 기능
