Repository SWM-KAWAI-MANS/party-run-authentication-service, pull requests merged in 2023-09, with the labels that each got.

#32 멤버 이름을 변경하는 기능 추가
  src/main/java/online/partyrun/partyrunauthenticationservice/domain/member/controller/MemberController.java
  src/main/java/online/partyrun/partyrunauthenticationservice/domain/member/dto/MemberNameUpdateRequest.java
  src/main/java/online/partyrun/partyrunauthenticationservice/domain/member/entity/Member.java
  src/main/java/online/partyrun/partyrunauthenticationservice/domain/member/service/MemberService.java
  src/test/java/online/partyrun/partyrunauthenticationservice/domain/member/controller/MemberControllerTest.java
  src/test/java/online/partyrun/partyrunauthenticationservice/domain/member/entity/MemberTest.java
  src/test/java/online/partyrun/partyrunauthenticationservice/domain/member/service/MemberServiceTest.java
Labels: ✨ 기능

#33 로그 메시지 출력 및 슬랙 알림 설정
  build.gradle
  src/main/java/online/partyrun/partyrunauthenticationservice/domain/auth/controller/AuthController.java
  src/main/java/online/partyrun/partyrunauthenticationservice/domain/member/controller/MemberController.java
  src/main/java/online/partyrun/partyrunauthenticationservice/global/controller/HttpControllerAdvice.java
  src/main/java/online/partyrun/partyrunauthenticationservice/global/logging/LogAdvisor.java
  src/main/java/online/partyrun/partyrunauthenticationservice/global/logging/Logging.java
  src/main/java/online/partyrun/partyrunauthenticationservice/global/logging/RequestLogFormatter.java
  src/main/java/online/partyrun/partyrunauthenticationservice/global/logging/RequestLoggingFilter.java
  src/main/resources/application.yml
  src/main/resources/logback-spring.xml
Labels: ✨ 기능

#35 prd 환경에서 redis cluster 설정
  src/main/resources/application.yml
Labels: ✨ 기능

#36 application yml 파일 변경
  src/main/resources/application-dev.yml
  src/main/resources/application-local.yml
  src/main/resources/application-prd.yml
  src/main/resources/application-test.yml
  src/main/resources/application.yml
Labels: ♻️ 리팩토링

#34 feat: 프로필 사진 수정 API 구현
  build.gradle
  src/docs/asciidoc/auth.adoc
  src/main/java/online/partyrun/partyrunauthenticationservice/domain/member/controller/MemberController.java
  src/main/java/online/partyrun/partyrunauthenticationservice/domain/member/entity/Member.java
  src/main/java/online/partyrun/partyrunauthenticationservice/domain/member/entity/Profile.java
  src/main/java/online/partyrun/partyrunauthenticationservice/domain/member/exception/InvalidFileStreamException.java
  src/main/java/online/partyrun/partyrunauthenticationservice/domain/member/exception/InvalidMultipartImageException.java
  src/main/java/online/partyrun/partyrunauthenticationservice/domain/member/repository/ProfileRepository.java
  src/main/java/online/partyrun/partyrunauthenticationservice/domain/member/service/MemberProfileService.java
  src/main/java/online/partyrun/partyrunauthenticationservice/domain/member/service/MemberService.java
  src/main/java/online/partyrun/partyrunauthenticationservice/global/config/AsyncConfig.java
  src/main/java/online/partyrun/partyrunauthenticationservice/global/config/FirebaseConfig.java
  src/main/java/online/partyrun/partyrunauthenticationservice/global/config/MemberAuthorizationRegistry.java
  src/main/resources/application-dev.yml
  src/main/resources/application-local.yml
  src/main/resources/application-prd.yml
  src/main/resources/application-test.yml
  src/main/resources/application.yml
  src/test/java/online/partyrun/partyrunauthenticationservice/TestConfig.java
  src/test/java/online/partyrun/partyrunauthenticationservice/domain/auth/controller/ControllerTestConfig.java
  src/test/java/online/partyrun/partyrunauthenticationservice/domain/member/controller/MemberControllerTest.java
  src/test/java/online/partyrun/partyrunauthenticationservice/domain/member/service/MemberProfileServiceTest.java
  src/test/java/online/partyrun/partyrunauthenticationservice/domain/member/service/MemberServiceTest.java
Labels: ✨ 기능

#39 refresh token 관련 로직을 수정한다.
  build.gradle
  src/main/java/online/partyrun/partyrunauthenticationservice/domain/auth/repository/RefreshTokenRepository.java
  src/main/java/online/partyrun/partyrunauthenticationservice/domain/auth/service/firebase/FirebaseAuthService.java
  src/main/java/online/partyrun/partyrunauthenticationservice/domain/token/entity/RefreshToken.java
  src/main/java/online/partyrun/partyrunauthenticationservice/domain/token/exception/EmptyStringException.java
  src/main/java/online/partyrun/partyrunauthenticationservice/domain/token/repository/RefreshTokenRepository.java
  src/main/resources/application-test.yml
  src/test/java/online/partyrun/partyrunauthenticationservice/domain/auth/repository/RefreshTokenRepositoryTest.java
  src/test/java/online/partyrun/partyrunauthenticationservice/domain/auth/service/FirebaseAuthServiceTest.java
  src/test/java/online/partyrun/partyrunauthenticationservice/domain/token/entity/RefreshTokenTest.java
Labels: ♻️ 리팩토링

#40 fix : update spring-security-authorization-manager
  build.gradle
Labels: ✨ 기능, 🐛 버그

#41 fix : redis properties 변경
  src/main/resources/application-prd.yml
Labels: 🐛 버그

#42 fix : defalut image url 변경
  src/main/java/online/partyrun/partyrunauthenticationservice/domain/member/entity/Profile.java
Labels: ♻️ 리팩토링

#43 ci cd prd 설정
  .github/workflows/build-docker-image-prd.yml
  .github/workflows/cd-prd.yml
Labels: 🏭인프라
